---
name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - v*  # Only run on version tags like v1.2.3
  workflow_dispatch:  # Allow manual triggering if needed
jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Build release binary
        run: cargo build --release
      - name: Rename binary for platform
        run: mv target/release/wave wave-${{ matrix.os }}
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: wave-${{ matrix.os }}
          path: wave-${{ matrix.os }}
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: wave-ubuntu-latest
          path: ./artifacts
      - name: Download macOS binary
        uses: actions/download-artifact@v4
        with:
          name: wave-macos-latest
          path: ./artifacts


      # Create GitHub Release and upload binaries
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/wave-ubuntu-latest
            ./artifacts/wave-macos-latest
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 